import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f7f7fb' },
  modeBar: {
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 2,
    borderRadius: 12,
    backgroundColor: '#111827',
    paddingVertical: 10,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modeBarText: { color: 'white', fontWeight: '700', flex: 1, marginRight: 10 },
  modeBarBtn: {
    backgroundColor: 'white',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
  },
  modeBarBtnText: { color: '#111827', fontWeight: '800' },

  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 12,
  },
  gameName: { fontSize: 16, fontWeight: '700', color: '#111827' },
  gameNameInput: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 16,
    minWidth: 150,
  },
  handText: { fontSize: 16, fontWeight: '600', color: '#374151' },
  listContent: { paddingHorizontal: 16, paddingBottom: 24 },
  emptyWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
  },
  emptyHint: { textAlign: 'center', color: '#6b7280', marginTop: 8 },
  headerRightRow: { flexDirection: 'row' },
  kebabBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: 'transparent',
    borderRadius: 999,
  },
  kebabText: { fontSize: 22, lineHeight: 22, color: '#111827' },
  headerBtnMargin: { marginRight: 8 },
  footerWrap: { paddingTop: 6, paddingBottom: 24 },
  footerBtn: {
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  footerBtnText: { color: 'white', fontWeight: '700', fontSize: 16 },
  btnPrimary: { backgroundColor: '#2563eb' },
});
